# Deployment
apiVersion: apps/v1
kind: Deployment

metadata:
  name: query-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: query

  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: hvitoi/blog-query

---
# ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: query-clusterip
spec:
  type: ClusterIP
  selector:
    app: query
  ports:
    - name: query
      protocol: TCP
      port: 3000
      targetPort: 3000
