apiVersion: v1
kind: Pod
metadata:
  name: projected-volume
  namespace: kaniko
spec:
  nodeName: mynode
  containers:
    - image: nginx
      name: projected-volume
      volumeMounts:
        - name: cluster-fs
          mountPath: /cluster-fs
  volumes:
    - name: cluster-fs
      hostPath:
        path: /
        type: Directory
