apiVersion: apps/v1
kind: Deployment

metadata:
  name: nats-depl

spec:
  replicas: 1

  selector:
    matchLabels:
      app: nats

  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats-streaming
          args: [
              '-p',
              '4222',
              '-m',
              '8222',
              '-hbi', # hard bit - How often the server will make a hb request to the clients (health check to make sure the clients are still running)
              '5s',
              '-hbt', # hard bit - How long the clients have to respond the hb
              '5s',
              '-hbf', # hard bit - How many times each client can fail before it's considered dead
              '2',
              '-SD',
              '-cid', # ClusterID: name of the cluster
              'ticketing', # Name of the cluster
            ] # argv to the docker container run
---
apiVersion: v1
kind: Service

metadata:
  name: nats-svc

spec:
  type: ClusterIP

  selector:
    app: nats

  ports:
    - name: client # Client to receive the events and manage channels
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring # Page to monitor the cluster (Server, clients, channels) http://localhost:8222/streaming
      protocol: TCP
      port: 8222
      targetPort: 8222
