version: "3.7"
services:

  rabbitmq:
    image: rabbitmq:3.8.12-management
    mem_limit: 300m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: 
      - currency-network

  naming-server:
    image: hvitoi/ms-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks: 
      - currency-network

  zipkin:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks: 
      - currency-network
    environment: 
      RABBIT.URI: amqp://guest:guest@rabbitmq:5672
    depends_on: 
      - rabbitmq

  api-gateway:
    image: hvitoi/ms-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    environment: 
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411
      RABBIT.URI: amqp://guest:guest@rabbitmq:5672
      SPRING.RABBITMQ.HOST: rabbitmq
      SPRING.ZIPKIN.SENDER.TYPE: rabbit
    ports:
      - "8765:8765"
    networks: 
      - currency-network
    depends_on: 
      - naming-server
      - rabbitmq

  currency-exchange:
    image: hvitoi/ms-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    environment: 
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411
      RABBIT.URI: amqp://guest:guest@rabbitmq:5672
      SPRING.RABBITMQ.HOST: rabbitmq
      SPRING.ZIPKIN.SENDER.TYPE: rabbit
    ports:
      - "8000:8000"
    networks: 
      - currency-network
    depends_on: 
      - naming-server
      - rabbitmq

  currency-conversion:
    image: hvitoi/ms-currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    environment: 
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411
      RABBIT.URI: amqp://guest:guest@rabbitmq:5672
      SPRING.RABBITMQ.HOST: rabbitmq
      SPRING.ZIPKIN.SENDER.TYPE: rabbit
    ports:
      - "8100:8100"
    networks: 
      - currency-network
    depends_on: 
      - naming-server
      - rabbitmq

networks:
  currency-network: {}