apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        [
          "--dockerfile=/workspace/dockerfile",
          "--context=dir://workspace",
          "--destination=docker.io/teste-kaniko:latest",
        ]
        # --no-push
      volumeMounts:
        - name: dockerfile-storage
          mountPath: /workspace
        - name: docker-config
          mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
    - name: dockerfile-storage
      persistentVolumeClaim:
        claimName: kaniko-pvc
    - name: docker-config
      secret:
        secretName: docker-config
