kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kaniko-pvc
  namespace: kaniko
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: kaniko-sc
