# This playbook update the table in the mysql container

- hosts: web1
  tasks:
    - name: Transfer template to web server
      template:
        src: table.j2
        dest: /var/www/html/index.php
