apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-toolkit
spec:
  template:
    spec:
      containers:
        - name: devops-toolkit
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 80m
              memory: 128Mi
