[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mypackage"
version = "0.1.0"
description = "A simple example package"
authors = [{ name = "Henry", email = "henry@example.com" }]
dependencies = ["requests>=2.31", "numpy>=1.25"]
requires-python = ">=3.8"
