apiVersion: v1
kind: Service
metadata:
  name: currency-conversion
spec:
  type: NodePort
  selector:
    app: currency-conversion
  ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100
      nodePort: 31001
