apiVersion: v1
kind: Service
metadata:
  name: currency-exchange
spec:
  type: NodePort
  selector:
    app: currency-exchange
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31000
