from langchain.chat_models import init_chat_model
from langchain.messages import AIMessage, HumanMessage, SystemMessage

# https://docs.langchain.com/oss/python/langchain/messages#message-prompts


# Roles
#   - [SystemMessage]: Tells the model how to behave and provide context for interactions
#   - [HumanMessage]:  Represents user input and interactions with the model. It can be text, images, etc
#   - [AIMessage]:     Responses generated by the model, including text content, tool calls, and metadata
#   - [ToolMessage]:   Represents the outputs of tool calls


llm = init_chat_model("anthropic:claude-sonnet-4-6")

messages = [
    SystemMessage("You are a helpful assistant"),
    HumanMessage("Can you help me?"),
    AIMessage("I'd be happy to help you with that question!"),
    HumanMessage("Great! What's 2+2?"),
]

messages2 = [
    ("system", "You are a helpful assistant"),
    ("user", "Can you help me?"),
    ("assistant", "I'd be happy to help you with that question!"),
    ("user", "Great! What's 2+2?"),
]

messages3 = [
    {
        "role": "system",
        "content": "You are a helpful assistant",
    },
    {
        "role": "user",
        "content": "Can you help me?",
    },
    {
        "role": "assistant",
        "content": "I'd be happy to help you with that question!",
    },
    {
        "role": "user",
        "content": "Great! What's 2+2?",
    },
]

response: AIMessage = llm.invoke(messages)
print(response.content)

# Or you can invoke with a simple text prompt...
# https://docs.langchain.com/oss/python/langchain/messages#text-prompts
# Text prompts are strings, ideal for straightforward generation tasks where you don't need to retain conversation history.
# it's automatically wrapped in a HumanMessage
response = llm.invoke("Write a haiku about spring")
print(response.content)
