# - `secrets` must be added to Repo Settings/Secrets. E.g.
#   - JWT keys
#   - API keys
#   - Docker credentials
# - Secrets are encrypted and only exposed to selected actions
# - Secrets are NOT passed to workflows triggered by PR

name: deploy-myservice

on:
  push:
    branches:
      - master
    paths:
      - "myservice/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repository
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t hvitoi/myservice myservice

      - name: Login to DockerHub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to DockerHub
        run: docker push hvitoi/myservice

      - name: Setup Digital Ocean doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Create kubectl context
        run: doctl kubernetes cluster kubeconfig save mycluster

      - name: Restart the deployment
        run: kubectl rollout restart deployment myservice-depl
