name: tests # Name of the workflow

on: pull_request # Trigger on pull request (open, closed, updated)

jobs:
  build: # Build a container
    runs-on: ubuntu-latest # with ubuntu
    steps:
      - uses: actions/checkout@v2 # take all the code in the repo
      - run: cd auth && npm install && npm run test:ci # Run the tests for auth
