version: "3"
services:
  prometheus:
    image: prom/prometheus
    # network_mode: host
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    # network_mode: host
    ports:
      - 3000:3000
    env_file:
      - ./grafana/grafana.env
  app:
    build: ./app/
    ports:
      - 8080:8080
