apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: { { .Release.Name } }
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: { { .Values.ingress.host } }
      http:
        paths:
          - backend:
              service:
                name: { { .Release.Name } }
                port:
                  number: 80
