apiVersion: apps/v1
kind: Deployment
metadata:
  name: asb
  namespace: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asb
  template:
    metadata:
      labels:
        app: asb
    spec:
      containers:
        - name: asb
          image: docker.io/image
          #imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: asb
  namespace: playground
  labels:
    app: asb
spec:
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 32205
  selector:
    app: asb
