apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: test-resilience-example-se
spec:
  hosts:
    - example.com
  ports:
    - number: 80
      name: http-port
      protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: test-resilience-example-vs
spec:
  hosts:
    - example.com
  http:
    - route:
        - destination:
            host: example.com
      timeout: 1s
