apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: henry
  region: us-east-1
  version: "1.31"

managedNodeGroups:
  - name: my-node-group
    instanceType: t3.small
    # instanceTypes: ["t3.small", "t3.medium"]
    minSize: 2
    desiredCapacity: 2
    maxSize: 4
    privateNetworking: true
    volumeSize: 5
    spot: true

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: eks-pod-identity-agent
  - name: aws-ebs-csi-driver
    wellKnownPolicies: # Adds an IAM service account
      ebsCSIController: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
    logRetentionInDays: 30
