apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: foo
  region: us-east-1
  version: "1.31" # latest if not provided

managedNodeGroups:
  - name: bar
    instanceType: t3.small
    # instanceTypes: ["t3.small", "t3.medium"]
    minSize: 2
    desiredCapacity: 2
    maxSize: 4
    volumeSize: 20
    privateNetworking: true
    spot: true
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true

addons:
  - name: kube-proxy # enabled by default
  - name: coredns # enabled by default
  - name: vpc-cni # enabled by default
  - name: eks-pod-identity-agent
  - name: aws-ebs-csi-driver
    wellKnownPolicies: # Adds an IAM service account
      ebsCSIController: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
    logRetentionInDays: 30
